
                ifndef _CONFIG_INCLUDE_
                define _CONFIG_INCLUDE_

                include "AY.inc"
                include "BASIC.inc"
                include "TRDOS.inc"
                include "Port_1FFD.inc"
                include "Port_7FFD.inc"
                include "Port_DFFD.inc"
                include "Port_FDFD.inc"
                include "ZX-Spectrum.inc"

                endif ; ~_CONFIG_INCLUDE_
