
                ifndef _MACRO_INCLUDE_
                define _MACRO_INCLUDE_

                include "Basic.inc"
                include "Debug.inc"
                include "Flags.inc"
                include "Assets.inc"
                include "Memory.inc"
                include "Screen_.inc"
                include "Interrupt.inc"
                include "Functions.inc"

                include "Page/Include.inc"

                endif ; ~_MACRO_INCLUDE_
