
                ifndef _STRUCT_BASE_INCLUDE_
                define _STRUCT_BASE_INCLUDE_

                include "Size.inc"
                include "Value.inc"
                include "Time.inc"
                include "Flags.inc"
                include "Disk.inc"
                include "Sprite.inc"
                include "Address.inc"
                include "Assets.inc"
                include "Item_ID.inc"
                include "Vector8.inc"
                include "Vector16.inc"
                include "AABB.inc"
                include "Location8.inc"
                include "Location16.inc"
                include "Location32.inc"
                include "Location40.inc"

                endif ; ~_STRUCT_BASE_INCLUDE_
