
                ifndef _CONST_MEMORY_MAP_PAGE_3_
                define _CONST_MEMORY_MAP_PAGE_3_

                ;   +-------+----------------------------+-------+
                ;   | #C000 |                            | #0000 |
                ;   +-------+----------------------------+-------+


                module Size
                endmodule

                module Page3
                endmodule

                module Adr
                endmodule

                endif ; ~_CONST_MEMORY_MAP_PAGE_3_
