
                ifndef _CONST_MEMORY_MAP_PAGE_1_
                define _CONST_MEMORY_MAP_PAGE_1_

                ;   +-------+----------------------------+-------+
                ;   | #C000 |                            | #0000 |
                ;   +-------+----------------------------+-------+

                module Page
                endmodule

                module Size
                endmodule

                module Adr
                endmodule

                endif ; ~_CONST_MEMORY_MAP_PAGE_1_
