
                ifndef _CONST_MEMORY_MAP_PAGE_7_
                define _CONST_MEMORY_MAP_PAGE_7_

                ;   +-------+------------------------------------------+-------+
                ;   | #С000 |                            Shadow Screen | #1B00 |
                ;   +-------+------------------------------------------+-------+
                
                module Page
                endmodule

                module Size
                endmodule

                module Adr
                endmodule

                endif ; ~_CONST_MEMORY_MAP_PAGE_7_
