
                ifndef _KERNEL_INCLUDE_MEMORY_PAGES_
                define _KERNEL_INCLUDE_MEMORY_PAGES_
SetPage         EQU Bootloader.KernelMinimal.Memory.SetPage
.Extended       EQU Bootloader.KernelMinimal.Memory.Extended
GetPage         EQU Bootloader.KernelMinimal.Memory.GetPage
SetPage0        EQU Bootloader.KernelMinimal.Memory.SetPage0
SetPage1        EQU Bootloader.KernelMinimal.Memory.SetPage1
SetPage3        EQU Bootloader.KernelMinimal.Memory.SetPage3
SetPage4        EQU Bootloader.KernelMinimal.Memory.SetPage4
SetPage5        EQU Bootloader.KernelMinimal.Memory.SetPage5
SetPage6        EQU Bootloader.KernelMinimal.Memory.SetPage6
SetPage7        EQU Bootloader.KernelMinimal.Memory.SetPage7

                endif ; ~_KERNEL_INCLUDE_MEMORY_PAGES_
