
                ifndef _BUILDER_BUILD_
                define _BUILDER_BUILD_

                display "Building..."

                include "Assets/Building_.inc"

                display "-------------------------------------------------------------------------------------------------------------------------------"

                labelslist "D:/Work/spectrum/unreal/user.l"

                endif ; ~_BUILDER_BUILD_
