
                ifndef _ASSETS_PACKING_CODE_INCLUDE_
                define _ASSETS_PACKING_CODE_INCLUDE_

                ; чёткий порядо касположения ресурсов
                include "Original/Kernel/Pack_Kernel.inc"                       ; ASSETS_ID_KERNEL
                include "Original/Pages/Pack_Page0.inc"                         ; ASSETS_ID_PAGE_0

                endif ; ~_ASSETS_PACKING_CODE_INCLUDE_
